apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-pv
  namespace: media-server
spec:
  capacity:
    storage: 200Gi  # Ajusta esto según tus necesidades
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Esto permite que el volumen sea leído y escrito por múltiples nodos
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-server-nfs
  nfs:
    path: /srv/nfs/shared/media-server  # La ruta al directorio compartido en el servidor NFS
    server: 10.70.154.1  # La dirección IP del servidor NFS
